### ISSUE TITLE
Create Rule Based System Agent

### ISSUE THREAD

**Issue by paolotron** [paolotron/Drop-Hanabi#3]
create a new player based on a rule based system strategy

**Comment by Alkio84** [comment]
Useful papers of state-of-the-art methods fo hanabi:
[SmartBot](https://github.com/Quuxplusone/Hanabi). SmartBot is a rule-based agent that tracks the publicly known information about each player’s cards. Tracking public knowledge allows SmartBot to reason about what other players may do, and what additional knowledge it gains from its specific view of the game. Among other things, this enables SmartBot to play/discard cards that its partners do not know that it knows are safe to play/discard, thereby preventing partners from wasting a hint to signal as much. However, this tracking assumes all other players are using SmartBot’s policy. When this assumption does not hold, as in the ad-hoc team setting, SmartBot can fall into false or impossible beliefs. For example, SmartBot can believe one of its cards has no valid value as all possible cards are inconsistent with the observed play according to SmartBot’s convention. Finally, note that SmartBot has a parameter specifying if it should attempt uncertain plays that may cost a life. Risking lives increases the frequency of perfect games while reducing average score, except in two player games where it is better on both criteria. Our SmartBot results only risks lives in the two player setting.
[HatBot](https://quuxplusone.github.io/blog/images/how-to-make-the-perfect-fireworks-display.pdf)  and [WTFWThat](https://github.com/WuTheFWasThat/hanabi.rs). HatBot uses a technique often seen in coding theory and “hat puzzles”. When giving hints, HatBot uses a predefined protocol to determine a recommended action for all other players (i.e., play or discard for one of a player’s cards). This joint recommendation is then encoded by summing the indices for the individual recommendations and using modular arithmetic. The encoded joint recommendation is mapped to different hints that HatBot could make, specifically, whether it reveals the colour or rank of a card for each other player. Since each player can view everyone’s cards but their own, they can reconstruct the action recommended to them by figuring out what would have been recommended to the other players based on HatBot’s convention, which HatBot assumes they know and use. Although this convention is not very intuitive for human players, it would still be possible for humans to learn and follow. Cox and colleagues also introduce an “information strategy” using a similar encoding mechanism to directly convey information about each player’s cards (as opposed to a recommended action), however it requires additional bookkeeping that makes it impractical for humans to use. As originally proposed, both the recommendation and information strategies were tailored for playing 5-player Hanabi. However, a variant of the information strategy, called WTFWThat, can play two through five players. These benchmarks more provide a lower-bound for optimal play than a baseline suggestive of human performance.
[FireFlower](https://github.com/lightvector/fireflower). FireFlower implements a set of human-style conventions (detailed in AppendixA.1  ). The bot keeps track of both private and common knowledge, including properties of cards that are implied by the common knowledge of what the conventions entail. Using this, FireFlower performs a 2-ply search over all possible actions with a modelled probability distribution over what its partner will do in response, and chooses the action that maximises the expected value of an evaluation function. The evaluation function takes into account the physical state of the game as well as the belief state. For example, if there is a card in the partner’s hand that is commonly known (due to inference from earlier actions) to be likely to be playable, then the evaluation function’s output will be much higher if it is indeed playable than if it is not. FireFlower uses a few additional conventions for three and four players, but avoids the hat-like strategies in favour of conventions that potentially allow it to partner more naturally with humans. According to Fireflower’s creator, it is designed with a focus on maximising the win probability, rather than average score.

**Comment by paolotron** [comment]
HatBot and WTFWThat use an hat strategy that is incompatible with the goal of our project as we cannot rely on previously agreed encoding patterns.
SmartBot and FireFlower seem promising and we could take inspiration

**Comment by Alkio84** [comment]
Some useful conventions:
• Hints generally indicate play cards, and generally newer cards first.
• Hints “chain” on to other hints, e.g., if A hints to B a playable red 2 as red, then
B might infer that it is indeed the red 2, and then hint back to A a red 3 in A’s
hand as red, expecting A to believe it is a red 3 to play it after B plays its red 2.
• When discarding, discard provably useless cards, otherwise the oldest “unprotected” card.
• Hints about the oldest unprotected card “protect” that card, with many exceptions
where it instead means play.
• Hints about garbage cards indicate “protect” cards older than it.
• Deliberately discarding known playable cards signals to the partner that they have
a copy of that card (with enough convention-based specificity on location that they
may play it with absolutely no actual hints).
• In many cases, hints about cards that have already been hinted change the belief
about those cards in various ways such that the partner will likely change what
they do (in accordance with the broader heuristic that one usually should give a
hint if and only if they would like to change the partner’s future behaviour).
